import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

import { IoBagSharp } from 'react-icons/io5';
import {
  SiDocker,
  SiExpress,
  SiFramer,
  SiGit,
  SiGithub,
  SiLinkedin,
  SiLinux,
  SiMaterialui,
  SiMongodb,
  SiNextdotjs,
  SiNodedotjs,
  SiPostgresql,
  SiReact,
  SiRedux,
  SiTypescript,
  SiVisualstudiocode,
} from 'react-icons/si';

import { AiFillPlayCircle } from 'react-icons/ai';
import imageFace from '../assets/profile.png';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <div className={styles.container__myprofile}>
          <Image
            width={300}
            height={300}
            className={styles.myface}
            src={imageFace}
            alt={'my-face'}
            objectFit="cover"
          />
          <div className={styles.container__info}>
            <div>
              <h1 className={styles.myName}>Jean Pierre Huaman Gomez</h1>
              <span className={styles.flag}>Full Stack Developer</span>
            </div>
            <div className={styles.contact__data}>
              <p>
                <strong>Correo:</strong> jeanpier.dev@outlook.com
              </p>
              <p>
                <strong>Tel:</strong> +51 935797308
              </p>
              <p>
                <strong>Ciudad:</strong> Lima - Perú
              </p>
            </div>
            <div className={styles.container__icons}>
              <a
                href="https://github.com/JeanPierHG"
                target={'_blank'}
                rel={'noreferrer'}
              >
                <SiGithub />
              </a>
              <a
                href="https://www.linkedin.com/in/jeanpierdev/"
                target={'_blank'}
                rel={'noreferrer'}
              >
                <SiLinkedin />
              </a>
              <a
                href="https://myportfolio-jean.vercel.app/"
                target={'_blank'}
                rel={'noreferrer'}
              >
                <IoBagSharp />
              </a>
            </div>
          </div>
        </div>
        <div className={styles.container__data}>
          <div className={styles.container__leftSide}>
            <div className={styles.container__skills}>
              <h2 className={styles.title__skils}>Tech Skills</h2>
              <div className={styles.container__tech}>
                <div>
                  <h3>Front-end</h3>
                  <ul>
                    <li>
                      <SiReact /> React
                    </li>
                    <li>
                      <SiRedux /> Redux
                    </li>
                    <li>
                      {' '}
                      <SiNextdotjs /> Next.js
                    </li>
                    <li>
                      {' '}
                      <SiTypescript /> TypeScript
                    </li>
                    <li>
                      {' '}
                      <SiFramer /> Framer-Motion
                    </li>
                    {/* <li>
                      <SiMaterialui /> MaterialUI
                    </li> */}
                    {/*  <li>
                      {' '}
                      <SiNextdotjs />
                      NextUI
                    </li> */}
                  </ul>
                </div>
                <div>
                  <h3>Back-end</h3>
                  <ul>
                    <li>
                      {' '}
                      <SiNodedotjs /> Node.js
                    </li>
                    <li>
                      <SiExpress /> Express
                    </li>
                    <li>
                      <SiPostgresql /> PostgreSQL
                    </li>
                    <li>
                      <SiMongodb /> Mongodb
                    </li>
                  </ul>
                </div>
                <div>
                  <h3>Tools</h3>
                  <ul>
                    <li>
                      {' '}
                      <SiVisualstudiocode /> Visual Studio Code
                    </li>
                    <li>
                      <SiLinux /> Linux
                    </li>
                    {/* DOCKER */}
                    {/* <li>
                      {' '}
                      <SiDocker />
                      Docker
                    </li> */}
                    <li>
                      <SiGit /> Git
                    </li>
                    <li>
                      <SiGithub /> Git-Hub
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            <div className={styles.container__competencias}>
              <h2>Competencias</h2>
              <div>
                <ul>
                  <li>Trabajo en equipo</li>
                  <li>Creatividad</li>
                  <li>Colaboración</li>
                  <li>Dedicación</li>
                  <li>Inteligencia Emocional</li>
                  <li>Proactividad</li>
                </ul>
              </div>
            </div>
            <div className={styles.container__idiomas}>
              <h2>Idiomas</h2>
              <ul>
                <li>Inglés A2 - Básico</li>
              </ul>
            </div>
            <div className={styles.container__hobbies}>
              <h2>Hobbies</h2>
              <ul>
                <li>Escuchar música.</li>
                <li>Ver películas.</li>
                <li>Salir con amigos.</li>
                <li>Jugar futbol.</li>
                <li>Ver tutoriales en youtube.</li>
              </ul>
            </div>
            <div className={styles.container__educacion_complementaria}>
              <h2>Cursos realizados</h2>
              <ul>
                <li>
                  Next.js: El Framework de React para producción. Udemy 2022
                </li>
                <li>
                  Node.js, Express, MongoDB & More: The Complete Bootcamp 2022.
                  Udemy. 2022.
                </li>
                <li>
                  The Complete JavaScript Course 2022: From Zero to Expert!.
                  Udemy. 2021.
                </li>
                <li>
                  Advanced CSS and Sass: Flexbox, Grid, Animations and More!.
                  Udemy. 2021.
                </li>
                <li>
                  Build Responsive Real-World Websites with HTML and CSS. Udemy.
                  2020.
                </li>
              </ul>
            </div>
          </div>
          <div className={styles.container__history}>
            <div className={styles.container__proyectos}>
              <h2>Proyectos</h2>
              <div className={styles.container__proyecto}>
                <div>
                  <div>
                    <h3>Full Stack Developer - Food App Recipes</h3>
                    <span>Henry Bootcamp, Buenos Aires, Argentina.</span>
                  </div>
                  <span> 04/22 - 05/22</span>
                </div>
                <ul>
                  <li>
                    Diseñar y desarrollar una App de recetas que incluía:
                    búsquedas, filtrados, ordenamientos y creación.
                  </li>
                  <li>
                    Tecnologías usadas: React, Redux, Css, Express, PostgreSQL y
                    Sequelize.
                  </li>
                  <li>
                    Soft Skills obtenidas: dedicación, innovación, gestión del
                    tiempo y proactividad.
                  </li>
                </ul>
                <div className={styles.iconsProyect}>
                  <a href="https://github.com/JeanPierHG/proyectFood">
                    <SiGithub />
                  </a>
                  <a
                    href="https://food-recipesapp.vercel.app/"
                    target={'_blank'}
                    rel="noreferrer"
                  >
                    <AiFillPlayCircle />
                  </a>
                </div>
              </div>
              <div className={styles.container__proyecto}>
                <div>
                  <div>
                    <h3>Full Stack Developer - Grow-Up Libros App </h3>
                    <span>Henry Bootcamp, Buenos Aires, Argentina.</span>
                  </div>
                  <span> 06/22 - 07/22</span>
                </div>
                <ul>
                  <li>
                    Diseñar y desarrollar una App para personas que buscan
                    libros que incluía: login, listado de productos, pasarela de
                    pago, envío de mails, filtros por género, ordenamientos por
                    rating, ventas, precio y toda la parte de administrador para
                    que el dueño pueda manejar sus órdenes, usuarios y sus
                    productos
                  </li>
                  <li>
                    Esta aplicación fue creada en conjunto con varios
                    desarrolladores, se implementó la metodología ágil Scrum y
                    se usó la aplicación Asana para la gestión del proyecto.
                  </li>
                  <li>
                    Tecnologías usadas: React, Redux y Material UI, MongoDB,
                    Mongo Atlas, Mongoose, Express, NodeMailer y Mercado Pago.
                  </li>
                  <li>
                    Soft Skills obtenidas: orientación al cliente, planificación
                    y organización, análisis de problemas, colaboración y
                    cooperación.
                  </li>
                </ul>
                <div className={styles.iconsProyect}>
                  <a
                    href="https://github.com/JeanPierHG/E-Commerce-Books"
                    target={'_blank'}
                    rel="noreferrer"
                  >
                    <SiGithub />
                  </a>
                  <a
                    href="https://e-commerce-books.vercel.app/"
                    target={'_blank'}
                    rel="noreferrer"
                  >
                    <AiFillPlayCircle />
                  </a>
                </div>
              </div>
            </div>
            <div className={styles.container__educacion}>
              <h2>Educación Profesional</h2>
              <ul>
                <li>
                  Full Stack Developer. Henry Bootcamp. 700 horas de cursado
                  teórico-práctico. 2022.
                </li>
                <li>
                  {' '}
                  Sistemas e Informática. Instituto Superior SISE. 2018 - 2019.
                </li>
              </ul>
            </div>
          </div>
        </div>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
