import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import { IoBagSharp } from 'react-icons/io5'
import {
  SiDocker,
  SiExpress,
  SiFramer,
  SiGit,
  SiGithub,
  SiLinkedin,
  SiLinux,
  SiMaterialui,
  SiMongodb,
  SiNextdotjs,
  SiNodedotjs,
  SiPostgresql,
  SiReact,
  SiRedux,
  SiTypescript,
  SiVisualstudiocode,
} from 'react-icons/si'
import imageFace from '../assets/profile.png'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.container}>
        <div className={styles.container__myprofile}>
          <Image
            width={300}
            height={300}
            className={styles.myface}
            src={imageFace}
            alt={'my-face'}
            objectFit='cover'
          />
          <div className={styles.container__info}>
            <div>
              <h1 className={styles.myName}>Jean Pierre Huaman Gomez</h1>
              <span className={styles.flag}>Full Stack Developer</span>
            </div>
            <div className={styles.contact__data}>
              <p>
                <strong>Correo:</strong> jeanpier.dev@outlook.com
              </p>
              <p>
                <strong>Tel:</strong> +51 935797308
              </p>
              <p>
                <strong>Ciudad:</strong> Lima - Perú
              </p>
            </div>
            <div className={styles.container__icons}>
              <a
                href='https://github.com/JeanPierHG'
                target={'_blank'}
                rel={'noreferrer'}>
                <SiGithub />
              </a>
              <a
                href='https://www.linkedin.com/in/jeanpierdev/'
                target={'_blank'}
                rel={'noreferrer'}>
                <SiLinkedin />
              </a>
              <a
                href='https://myportfolio-jean.vercel.app/'
                target={'_blank'}
                rel={'noreferrer'}>
                <IoBagSharp />
              </a>
            </div>
          </div>
        </div>
        <div className={styles.container__data}>
          <div className={styles.container__leftSide}>
            <div className={styles.container__skills}>
              <h2 className={styles.title__skils}>Tech Skills</h2>
              <div className={styles.container__tech}>
                <div>
                  <h3>Front-end</h3>
                  <ul>
                    <li>
                      <SiReact /> React
                    </li>
                    <li>
                      <SiRedux /> Redux
                    </li>
                    <li>
                      {' '}
                      <SiNextdotjs /> Next.js
                    </li>
                    <li>
                      {' '}
                      <SiTypescript /> TypeScript
                    </li>
                    <li>
                      {' '}
                      <SiFramer /> Framer-Motion
                    </li>
                    <li>
                      <SiMaterialui /> MaterialUI
                    </li>
                    <li>
                      {' '}
                      <SiNextdotjs />
                      NextUI
                    </li>
                  </ul>
                </div>
                <div>
                  <h3>Back-end</h3>
                  <ul>
                    <li>
                      {' '}
                      <SiNodedotjs /> Node.js
                    </li>
                    <li>
                      <SiExpress /> Express
                    </li>
                    <li>
                      <SiPostgresql /> PostgreSQL
                    </li>
                    <li>
                      <SiMongodb /> Mongodb
                    </li>
                  </ul>
                </div>
                <div>
                  <h3>Tools</h3>
                  <ul>
                    <li>
                      {' '}
                      <SiVisualstudiocode /> Visual Studio Code
                    </li>
                    <li>
                      <SiLinux /> Linux
                    </li>
                    <li>
                      {' '}
                      <SiDocker />
                      Docker
                    </li>
                    <li>
                      <SiGit /> Git
                    </li>
                    <li>
                      <SiGithub /> Git-Hub
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            <div className={styles.container__competencias}>
              <h2>Competencias</h2>
              <div>
                <ul>
                  <li>Trabajo en equipo</li>
                  <li>Creatividad</li>
                  <li>Colaboracion</li>
                  <li>Dedicación</li>
                  <li>Inteligencia Emocional</li>
                  <li>Proactividad</li>
                </ul>
              </div>
            </div>
            <div className={styles.container__hobbies}>
              <h2>Hobbies</h2>
            </div>
          </div>
          <div className={styles.container__history}>
            <div>
              <h2>Experienca Laboral</h2>
            </div>
          </div>
        </div>
      </main>

      <footer></footer>
    </div>
  )
}

export default Home
